# Generated by Django 4.0.4 on 2022-10-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
