# Generated by Django 4.0.4 on 2022-10-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_alter_pokemon_modified_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
